guard 'jekyll', :source => './src' do
  watch %r{^src/.*}
end

# this isn't working right now,
# so the workaround is to manually run 'compass watch src/_sass'
#guard 'compass', :project_path => './src/_sass', :configution_file => './src/_sass/config.rb' do
#  watch %r{^src/(.*)\.s[ac]ss}
#end
